name: Create a pull request and merge it  
on:
  push:
    branches:
      - feature/*
# jobs:
#   Automatically:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout the repo
#         uses: actions/checkout@v2
#       - name: Create Pull Request
#         uses: peter-evans/create-pull-request@v4
#         with:
#           token: ${{ secrets.USER_TOKEN }}
#           commit-message: Clean Code
#           title: Clean Code
#           body: Clean all codes and make sure it works well.
#           base: master
#           labels: automated-pr
#           branch: feature/forpr
#           delete-branch: false
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Create Pull Request
        id: cpr
        uses: ./
        with:
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          milestone: 1
          draft: false
          branch: feature/forpr
          delete-branch: false